/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certificate { 'expiryDate' : Time, 'name' : string }
export type JobStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface SigningJob {
  'status' : JobStatus,
  'ipaFilename' : string,
  'certificateName' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addCertificate' : ActorMethod<[string, Time], undefined>,
  'getAllJobs' : ActorMethod<[], Array<SigningJob>>,
  'getAllJobsByCertificate' : ActorMethod<[], Array<SigningJob>>,
  'getCertificates' : ActorMethod<[], Array<Certificate>>,
  'getJobStatus' : ActorMethod<[string], JobStatus>,
  'submitSigningJob' : ActorMethod<[string, string], string>,
  'updateJobStatus' : ActorMethod<[string, JobStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];