/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const JobStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const SigningJob = IDL.Record({
  'status' : JobStatus,
  'ipaFilename' : IDL.Text,
  'certificateName' : IDL.Text,
});
export const Certificate = IDL.Record({
  'expiryDate' : Time,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCertificate' : IDL.Func([IDL.Text, Time], [], []),
  'getAllJobs' : IDL.Func([], [IDL.Vec(SigningJob)], ['query']),
  'getAllJobsByCertificate' : IDL.Func([], [IDL.Vec(SigningJob)], ['query']),
  'getCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
  'getJobStatus' : IDL.Func([IDL.Text], [JobStatus], ['query']),
  'submitSigningJob' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'updateJobStatus' : IDL.Func([IDL.Text, JobStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const JobStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const SigningJob = IDL.Record({
    'status' : JobStatus,
    'ipaFilename' : IDL.Text,
    'certificateName' : IDL.Text,
  });
  const Certificate = IDL.Record({ 'expiryDate' : Time, 'name' : IDL.Text });
  
  return IDL.Service({
    'addCertificate' : IDL.Func([IDL.Text, Time], [], []),
    'getAllJobs' : IDL.Func([], [IDL.Vec(SigningJob)], ['query']),
    'getAllJobsByCertificate' : IDL.Func([], [IDL.Vec(SigningJob)], ['query']),
    'getCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
    'getJobStatus' : IDL.Func([IDL.Text], [JobStatus], ['query']),
    'submitSigningJob' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'updateJobStatus' : IDL.Func([IDL.Text, JobStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };